#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-server
    password: "$6$oSqeZUJFYZG4xNIs$f4V423IUo.k8E8q5wk6HsqE4x/sxsK1Azd.YnNogwyVJdE65gDX16./DKVNwrfPN0oa7uyRf9fhLk7UyPTjK.0"
    username: nextocean
  ssh:
    install-server: true
    allow-pw: true
  late-commands:
    - curtin in-target -- apt update
    - curtin in-target -- sh -c 'cd /home/nextocean/Downloads && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && dpkg -i google-chrome-stable_current_amd64.deb'
    - curtin in-target -- sh -c 'cd /home/nextocean/Downloads && wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && sh Miniconda3-latest-Linux-x86_64.sh -b'
    - curtin in-target -- sh -c 'cd /home/nextocean/Downloads && wget https://download.teamviewer.com/download/linux/teamviewer-host_amd64.deb && dpkg -i teamviewer-host_amd64.deb'
