#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    username: joe
    password: $6$rounds=4096$uLC9TYc2v5o3N7jZ$P5MK2s0eQf.s/1e4N2uzos5OvKYP07AUmCG0YAmktyTbZQvD0ftakZaIuGPEPFAFvm4AXCrNk8cd2cNgvS1Zk/
  user-data:
    disable_root: false
    users:
      - name: joe
        passwd: $6$rounds=4096$uLC9TYc2v5o3N7jZ$P5MK2s0eQf.s/1e4N2uzos5OvKYP07AUmCG0YAmktyTbZQvD0ftakZaIuGPEPFAFvm4AXCrNk8cd2cNgvS1Zk/
        lock_passwd: false
        groups: sudo
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
  late-commands:
    - |
      echo "Downloading and installing Google Chrome"
      curl -o /home/joe/Downloads/google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dpkg -i /home/joe/Downloads/google-chrome-stable_current_amd64.deb || apt-get install -f -y
      chown joe:joe /home/joe/Downloads/google-chrome-stable_current_amd64.deb
  storage:
    layout:
      name: direct
  interactive-sections:
    - keyboard
    - timezone
