#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-server
    username: nextocean
    password: "$6$oSqeZUJFYZG4xNIs$f4V423IUo.k8E8q5wk6HsqE4x/sxsK1Azd.YnNogwyVJdE65gDX16./DKVNwrfPN0oa7uyRf9fhLk7UyPTjK.0"
  ssh:
    install-server: true
    allow-pw: true
  user-data:
    disable_root: false
    chpasswd:
      expire: false
    users:
      - default
      - name: nextocean
        lock_passwd: false
        groups: sudo
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
  late-commands:
    - |
      echo "nextocean ALL=(ALL) NOPASSWD:ALL" > /target/etc/sudoers.d/nextocean
    - |
      chroot /target /bin/bash -c "su - nextocean -c 'xdg-user-dirs-update'"
    - |
      chroot /target /bin/bash -c "su - nextocean -c 'cd ~/Downloads && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo dpkg -i google-chrome-stable_current_amd64.deb && sudo apt-get -f install -y'"
    - |
      chroot /target /bin/bash -c "su - nextocean -c 'cd ~/Downloads && wget https://download.teamviewer.com/download/linux/teamviewer_amd64.deb && sudo dpkg -i teamviewer_amd64.deb && sudo apt-get -f install -y'"
    - |
      chroot /target /bin/bash -c "su - nextocean -c 'cd ~/Downloads && wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3'"
