#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-server
    username: nextocean
    password: "$6$oSqeZUJFYZG4xNIs$f4V423IUo.k8E8q5wk6HsqE4x/sxsK1Azd.YnNogwyVJdE65gDX16./DKVNwrfPN0oa7uyRf9fhLk7UyPTjK.0"
  ssh:
    install-server: true
    allow-pw: true
  user-data:
    disable_root: false
    chpasswd:
      expire: false
    users:
      - default
      - name: nextocean
        groups: sudo
        shell: /bin/bash
  packages:
    - ubuntu-desktop
  late-commands:
    - |
      echo "Disabling show-home in GNOME Shell extension"
      chroot /target /bin/bash -c 'gsettings set org.gnome.shell.extensions.ding show-home false'
