#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-server
    username: nextocean
    password: "$6$oSqeZUJFYZG4xNIs$f4V423IUo.k8E8q5wk6HsqE4x/sxsK1Azd.YnNogwyVJdE65gDX16./DKVNwrfPN0oa7uyRf9fhLk7UyPTjK.0"
  ssh:
    install-server: true
    allow-pw: true
  user-data:
    disable_root: false
    chpasswd:
      expire: false
    users:
      - default
      - name: nextocean
        lock_passwd: false
        groups: sudo
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
  packages:
    - ubuntu-desktop
    - netcdf-bin
    - psensor
    - default-jre
    - libmbedtls-dev
    - htop
    - tmux
    - emacs
    - traceroute
    - build-essential
    - gnuplot
    - ssh
    - nmap
    - arp-scan
    - libminizip1
    - wakeonlan
    - tigervnc-scraping-server
    - wireshark
    - wget
    - qtbase5-dev 
    - qtchooser 
    - qt5-qmake 
    - qtbase5-dev-tools
  debconf-selections: |
    wireshark-common wireshark-common/install-setuid boolean false
  late-commands:
    - curtin in-target -- sh -c "gsettings set org.gnome.desktop.screensaver lock-enabled false"
    - curtin in-target -- sh -c "gsettings set org.gnome.desktop.screensaver idle-activation-enabled false"
    - curtin in-target -- sh -c "gsettings set org.gnome.desktop.session idle-delay 0"
    - curtin in-target -- sh -c "gsettings set org.gnome.settings-daemon.plugins.power idle-dim false"
    - curtin in-target -- sh -c "gsettings set org.gnome.shell.extensions.ding show-home false"
    - curtin in-target -- sh -c 'printf "[connectivity]\nuri=\ninterval=0\n" >> /etc/NetworkManager/NetworkManager.conf && systemctl restart NetworkManager'
    - curtin in-target -- sh -c "cd /home/nextocean/Downloads && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install -y ./google-chrome-stable_current_amd64.deb"
    - curtin in-target -- sh -c "sed -i 's/GRUB_DEFAULT=0/GRUB_DEFAULT=0/g' /etc/default/grub"
    - curtin in-target -- sh -c "sed -i 's/GRUB_TIMEOUT_STYLE=hidden/GRUB_TIMEOUT_STYLE=menu/g' /etc/default/grub"
    - curtin in-target -- sh -c "sed -i 's/GRUB_TIMEOUT=[0-9]*/GRUB_TIMEOUT=5/g' /etc/default/grub"
    - curtin in-target -- sh -c "sed -i 's/quiet splash//g' /etc/default/grub"
    - curtin in-target -- sh -c "apt-get update && apt-get install -y plymouth"
    - curtin in-target -- sh -c "update-initramfs -u"
    - curtin in-target -- sh -c "update-grub"
    - curtin in-target -- sh -c "sed -i 's|\*\.\*;auth,authpriv\.none\t\t-/var/log/syslog|$outchannel mysyslog,/var/log/syslog,10485760\n*.*;auth,authpriv.none\t\t:omfile:$mysyslog|g' /etc/rsyslog.d/50-default.conf"
    - curtin in-target -- sh -c "systemctl restart rsyslog.service"
    - curtin in-target -- sh -c "sed -i 's|#SystemMaxUse=|SystemMaxUse=10M|g' /etc/systemd/journald.conf"
    - curtin in-target -- sh -c "sed -i 's|#RuntimeMaxUse=|RuntimeMaxUse=10M|g' /etc/systemd/journald.conf"
    - curtin in-target -- sh -c 'apt update && apt upgrade -y && apt autoremove -y && apt autoclean && apt clean'
